se incluye imagen
raficorr/Recetario4 pull request #1
Opened 2022-02-17 22:14 UTC by rhrodriguezr

Se agrega imagen del regalo.

2022-02-17 22:21 UTC, rhrodriguezr reviewed
el archivo cumple

2022-02-17 22:21 UTC, rhrodriguezr commented
s

2022-02-17 22:21 UTC, rhrodriguezr commented
se encuentra bien

2022-02-18 02:00 UTC, raficorr requested changes
la imagen no cumple con lo solicitado

2022-02-18 02:04 UTC, merged